// Generated by Haxe
(function (console) { "use strict";
var PollsClient = function() {
	this.config = null;
	var _g = this;
	this.doc = window.document;
	this.doc.addEventListener("DOMContentLoaded",function() {
		electron_IPC.send("ready");
		_g.config = electron_IPC.sendSync("polls.get");
		_g.q1Input = _g.doc.getElementById("q1");
		_g.q2Input = _g.doc.getElementById("q2");
		_g.key1Input = _g.doc.getElementById("key1");
		_g.key2Input = _g.doc.getElementById("key2");
		_g.list1 = _g.doc.getElementById("list1");
		_g.list2 = _g.doc.getElementById("list2");
		_g.saveBtn = _g.doc.getElementById("save");
		_g.startBtn = _g.doc.getElementById("start");
		_g.stopBtn = _g.doc.getElementById("stop");
		_g.resetBtn = _g.doc.getElementById("reset");
		_g.showBtn = _g.doc.getElementById("show");
		_g.hideBtn = _g.doc.getElementById("hide");
		_g.startBtn.addEventListener("click",function(_) {
			_g.config = electron_IPC.sendSync("polls.start");
			_g.updateBtns();
		});
		_g.stopBtn.addEventListener("click",function(_1) {
			_g.config = electron_IPC.sendSync("polls.stop");
			_g.updateBtns();
		});
		_g.resetBtn.addEventListener("click",function(_2) {
			_g.config = electron_IPC.sendSync("polls.reset");
			_g.updateBtns();
		});
		_g.showBtn.addEventListener("click",function(_3) {
			_g.config = electron_IPC.sendSync("polls.show");
			_g.updateBtns();
		});
		_g.hideBtn.addEventListener("click",function(_4) {
			_g.config = electron_IPC.sendSync("polls.hide");
			_g.updateBtns();
		});
		_g.saveBtn.addEventListener("click",function(_5) {
			var cfg = { q1 : _g.q1Input.value, q2 : _g.q2Input.value, key1 : _g.key1Input.value, key2 : _g.key2Input.value};
			_g.config = electron_IPC.sendSync("polls.set",cfg);
			_g.updateBtns();
		});
		_g.updateBtns();
		var timer = new haxe_Timer(1000);
		timer.run = function() {
			_g.config = electron_IPC.sendSync("polls.get");
			_g.updateLists();
		};
	});
};
PollsClient.main = function() {
	var client = new PollsClient();
};
PollsClient.prototype = {
	updateBtns: function() {
		var _g = this.config.status;
		switch(_g) {
		case "not_running":
			this.stopBtn.style.display = "none";
			this.startBtn.style.display = "inline";
			this.resetBtn.style.display = "inline";
			this.saveBtn.style.display = "inline";
			break;
		case "running":
			this.stopBtn.style.display = "inline";
			this.startBtn.style.display = "none";
			this.resetBtn.style.display = "none";
			this.saveBtn.style.display = "inline";
			break;
		case "stopped":
			this.stopBtn.style.display = "none";
			this.startBtn.style.display = "inline";
			this.resetBtn.style.display = "inline";
			this.saveBtn.style.display = "inline";
			break;
		}
		var _g1 = this.config.visual;
		switch(_g1) {
		case "hidden":
			this.showBtn.style.display = "inline";
			this.hideBtn.style.display = "none";
			break;
		case "visible":
			this.hideBtn.style.display = "inline";
			this.showBtn.style.display = "none";
			break;
		}
		this.q1Input.value = this.config.q1;
		this.q2Input.value = this.config.q2;
		this.key1Input.value = this.config.key1;
		this.key2Input.value = this.config.key2;
		this.updateLists();
	}
	,updateLists: function() {
		this.list1.innerHTML = this.config.votes1.join("\n");
		this.list2.innerHTML = this.config.votes2.join("\n");
	}
};
var electron_IPC = require("ipc");
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.prototype = {
	run: function() {
	}
};
PollsClient.main();
})(typeof console != "undefined" ? console : {log:function(){}});
