// Generated by Haxe
(function (console) { "use strict";
var WheelClient = function() {
	this.config = null;
	var _g = this;
	this.doc = window.document;
	this.doc.addEventListener("DOMContentLoaded",function() {
		electron_IPC.send("ready");
		_g.config = electron_IPC.sendSync("wheel.get");
	});
};
WheelClient.main = function() {
	var client = new WheelClient();
};
var electron_IPC = require("ipc");
WheelClient.main();
})(typeof console != "undefined" ? console : {log:function(){}});
